### PR TITLE
Try again to correct the include paths

### PR DESCRIPTION
**Pull request by danpetry**
**Destination channel:** defaults

### Explanation of changes:

- Previous PR didn't work because the appropriate changes weren't made in the pkg-config file patch.
- Currently being verified by including the staging channel here during the libxml2 rebuild

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]
LGTM. I'll test downstream packages with it

**Review by SC426 — APPROVED** [review]

**Comment by danpetry** [comment]
@skupr-anaconda please ping me when you've tested some non-pkgconfig based packages

**Comment by skupr-anaconda** [comment]
Other packages I've rebuilt are fine with this fix.

But I'm waiting for `llvmdev` and `gdal`. They are blocked by a `conda-build` bug on `win64`, see https://github.com/AnacondaRecipes/llvmdev-feedstock/pull/15#issuecomment-2257595534 and https://github.com/AnacondaRecipes/gdal-feedstock/pull/25#issuecomment-2257625970. 
I guess that after fixing the conda-build bug both packages will succeed.

**Comment by danpetry** [comment]
@skupr-anaconda looks like this is working for llvmdev and gdal?

**Comment by skupr-anaconda** [comment]
> @skupr-anaconda looks like this is working for llvmdev and gdal?

Yes

**Pull request merged**
